### ISSUE TITLE
Ability to create a shareable URL

### ISSUE THREAD

**Issue by fabiandev** [fabiandev/typescript-playground#1]
Add a feature that either appends an encoded version of the editor contents to the URL in realtime or, e.g., by clicking on a button.

**Comment by aluanhaddad** [comment]
This is such an awesome tool and now that URLs are shareable, I will be using this over https://typescriptlang.org/play all the time.

Great work! ❤️

**Comment by fabiandev** [comment]
Thank you @aluanhaddad! :)
