### ISSUE TITLE
Suggestion: Horizontal scroll bar in javascript frame & rearrangement of the frames

### ISSUE THREAD

**Issue by lord-saumagen** [fabiandev/typescript-playground#13]
Dear Fabian Pirklbauer,

it would be nice to have the ability for horizontal scroll even in the javascript frame. If you deal with long lines of code the transpiled javascript often runs out of the frame. Since you didn't allow to scroll horizontal in the javascript frame, it's unnecessarily complicated to get a full view of the 
transpiled  TypeScript code.

It would also be nice if you could implement a function to rearrange the frames vertically. That way the 
horizontal space for both frames will become significant greater (double the size) and horizontal scrolling will become less important.

Once again, thank you for sharing your superb program.

Kind regards, Lord Saumagen.

**Comment by fabiandev** [comment]
You are right, while it's possible to scroll with the mouse or trackpad, the scrollbar is hidden by the overlapping `Run in new window button`. Will fix this asap.

Please open a separate issue for the rearrangement of editors, so I can consider that for a future version. Thanks!
