### ISSUE TITLE
Global `length` variable

### ISSUE THREAD

**Issue by bart5** [fabiandev/typescript-playground#14]
There is initialized global `length` variable equal 1.
![image](https://user-images.githubusercontent.com/23498460/57677879-2ef3a680-7628-11e9-9b6b-94c49cf60ef2.png)

**Comment by bart5** [comment]
Yeah, sorry. I was faster in pasting that here than thinking.

**Comment by fabiandev** [comment]
No worries, looks like to be an issue with [monaco-typescript](https://github.com/Microsoft/monaco-typescript) (or [monaco-editor](https://github.com/Microsoft/monaco-editor)).
