### ISSUE TITLE
How to add custom modules

### ISSUE THREAD

**Issue by cisaacson** [fabiandev/typescript-playground#17]
Is there an easy way to add my own modules to the playground so they are available? I would guess that I can install modules as normal in package.json and then use `import` statements, but I would like to create a custom build that already includes modules for a common environment we use.

Great job on the product by the way.

**Comment by fabiandev** [comment]
Hi @cisaacson, thanks for your feedback!

External packages would need to be made available to the typescript service of the editor. I would need to have a close look, but currently not supported by this project.

I haven't checked the possibilities with [`monaco-editor`](https://github.com/microsoft/monaco-editor) and [`monaco-typescript`](https://github.com/microsoft/monaco-typescript) there. I guess it should be possible somehow.

Happy for any findings and contributions on that :)

**Comment by cisaacson** [comment]
Thanks. For now I worked out another solution (a completely different approach), but this would be a good thing to know in the future.
