### ISSUE TITLE
Feature request: Display TypeScript version

### ISSUE THREAD

**Issue by aluanhaddad** [fabiandev/typescript-playground#2]
Greetings.
Thank you for this awesome tool.

Would it be possible to display the version of TypeScript that is in use?

**Comment by aluanhaddad** [comment]
@fabiandev awesome glad to hear that this is in the works. Also, thanks for the info about how, why, and which version in use.

**Comment by fabiandev** [comment]
That was actually easier than expected. The TypeScript version now shows up in the playground settings when clicking on the cogwheel. Also the default editor contents display the TypeScript version instead of the playground version.

**Comment by aluanhaddad** [comment]
Awesome! Amazing turn around time on this by the way 😃!
