### ISSUE TITLE
Change TypeScript version

### ISSUE THREAD

**Issue by fabiandev** [fabiandev/typescript-playground#9]
If possible add an option to choose from a number of TypeScript versions.

**Comment by cspotcode** [comment]
I think you can use unpkg to load any TypeScript version straight from npm.  You can even load a nightly development build, since those are all published to npm.

unpkg.com/typescript@next/lib/typescriptServices.js

**Comment by fabiandev** [comment]
This may be the way to go, however, currently `typescript-playground` uses the bundled version of [`monaco-editor`](https://github.com/Microsoft/monaco-editor) which itself uses [`monaco-typescript`](https://github.com/Microsoft/monaco-typescript). Will have to explore if external TypeScript services can be injected. PRs also very welcome.

**Comment by fabiandev** [comment]
TypeScript version can now be selected by adding `?ts={version}` to the URL, and available version can be found in [`versions.json`](https://github.com/fabiandev/typescript-playground/blob/master/versions.json). A way to select the version in the UI will be added soon.
